image: python:latest

stages:
  - build

build_job:
  stage: build
  before_script:
    - pip install pylode
  script:
    - cd docs/
    - mkdir build/
    - python generate_docs.py -o ./build/
  artifacts:
    paths:
      - docs/build/*
