image: python:latest

variables:
  DEPLOY_PATH: /opt/morphosource/root/public/terms/

stages:
  - build
  - deploy

build_job:
  stage: build
  before_script:
    - pip install pylode
  script:
    - cd docs/
    - mkdir build/
    - python generate_docs.py -o ./build/
  artifacts:
    paths:
      - docs/build/*

.deploy:
  stage: deploy
  script:
    - cp -R docs/build/* $DEPLOY_PATH

deploy_dev:
  extends: .deploy
  environment:
    name: development
    url: https://morphosource-dev.oit.duke.edu/
  tags:
    - development